### ISSUE TITLE
'Square brackets enclosed host' problem with Python

### ISSUE THREAD

**Issue by Parahexen** [httptoolkit/httptoolkit#106]
```
TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://[localhost:8123]
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new URL (internal/url.js:330:22)
    at /_/httptoolkit-server/node_modules/mockttp/src/server/mockttp-server.ts:115:31
    at call (/_/httptoolkit-server/node_modules/connect/index.js:239:7)
    at next (/_/httptoolkit-server/node_modules/connect/index.js:183:5)
    at /_/httptoolkit-server/node_modules/mockttp/src/util/request-utils.ts:317:5
    at call (/_/httptoolkit-server/node_modules/connect/index.js:239:7)
    at next (/_/httptoolkit-server/node_modules/connect/index.js:183:5)
    at Function.handle (/_/httptoolkit-server/node_modules/connect/index.js:186:3)
    at Server.app (/_/httptoolkit-server/node_modules/connect/index.js:51:37)
    at Server.emit (events.js:314:20)
    at Server.EventEmitter.emit (domain.js:486:12)
    at parserOnIncoming (_http_server.js:863:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at socketOnData (_http_server.js:581:22)
```

The upstream is python xmlrpclib, I cannot capture its traffic successfully.

**Comment by pimterry** [comment]
This was [fixed recently](https://github.com/httptoolkit/httptoolkit-server/commit/d4e402c0c2e040117ed1836e953d7f70f53e2704) - it should be resolved for server 1.1.0+. Thanks for reporting this, and do let me know if you find any other issues!
