### ISSUE TITLE
After some system updates of Linux Mint I can no longer connect to the JVM.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [httptoolkit/httptoolkit#139]
Hello, after some system updates of Linux Mint I can no longer connect to the JVM, although it was successful before. I am using Tomcat 8 + Oracle JDK 1.8 (I also successfully used OpenJDK and AdoptOpenJDK before). What can be the root of the problem?

```
$ inxi -F
System:
  Host: sergei-Z490-UD Kernel: 5.4.0-72-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
Machine:
  Type: Desktop Mobo: Gigabyte model: Z490 UD v: x.x 
  serial: <superuser/root required> UEFI: American Megatrends v: F5 
  date: 08/28/2020 
CPU:
  Topology: 6-Core model: Intel Core i5-10400F bits: 64 type: MT MCP 
  L2 cache: 12.0 MiB 
  Speed: 800 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800 
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] driver: nvidia v: 460.73.01 
  Display: x11 server: X.Org 1.20.9 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: GeForce GT 710/PCIe/SSE2 v: 4.6.0 NVIDIA 460.73.01 
Audio:
  Device-1: Intel Comet Lake PCH cAVS driver: snd_hda_intel 
  Device-2: NVIDIA GK208 HDMI/DP Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.0-72-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  driver: r8169 
  IF: enp5s0 state: down mac: 18:c0:4d:76:59:be 
  Device-2: TP-Link 802.11ac NIC type: USB driver: rtl88x2bu 
  IF: wlxd03745b0a80f state: up mac: d0:37:45:b0:a8:0f 
  IF-ID-1: docker0 state: up speed: N/A duplex: N/A mac: 02:42:42:08:71:40 
  IF-ID-2: veth051ef2f state: up speed: 10000 Mbps duplex: full 
  mac: b6:55:48:df:a2:e1 
Drives:
  Local Storage: total: 223.57 GiB used: 96.11 GiB (43.0%) 
  ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB 
Partition:
  ID-1: / size: 218.57 GiB used: 96.10 GiB (44.0%) fs: ext4 dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 37.0 C mobo: 16.8 C gpu: nvidia temp: 50 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 379 Uptime: 1h 49m Memory: 15.56 GiB used: 10.98 GiB (70.6%) 
  Shell: bash inxi: 3.0.38 

```

**Comment by pimterry** [comment]
Hi @sergey-prosvirnin thanks for reporting this. A few quick questions:

* Is it that the "Attach to JVM" option doesn't appear, or that it appears but it doesn't work when you select a target?
* What happens if you download the [jvm-http-proxy-agent JAR](https://github.com/httptoolkit/jvm-http-proxy-agent/releases/download/v1.1.1/http-proxy-agent-1.1.1-dist.jar) and run the below:
  ```bash
  java -Djdk.attach.allowAttachSelf=true -jar ./agent.jar self-test
  ```
* What about if you run that command using `$JAVA_HOME/bin/java ...`, or using other Java versions on your machine?

That test is what's used to detect whether we have a suitable Java version available, before the option is made activateable in the UI. As far as I know, if that test works with your Java environment then everything _should_ work OK, and if not then it should show some basic info about what's going wrong, and we can start from there.

**Comment by sergey-prosvirnin** [comment]
```
$ /home/sergei/.jdks/adopt-openj9-1.8.0_292/bin/java -Djdk.attach.allowAttachSelf=true -jar ./http-proxy-agent-1.1.1-dist.jar self-test
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com.sun.tools.attach.AgentLoadException
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:300)
	at java.lang.Class.getMethodHelper(Class.java:1287)
	at java.lang.Class.getMethod(Class.java:1230)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:951)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:896)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879)
	... 6 more

$ /usr/lib/jvm/jdk1.8.0_281/bin/java -Djdk.attach.allowAttachSelf=true -jar ./http-proxy-agent-1.1.1-dist.jar self-test
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more


$ /usr/lib/jvm/jdk1.8.0_281/bin/java -Djdk.attach.allowAttachSelf=true -jar ./http-proxy-agent-1.1.1-dist.jar self-test
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

```

**Comment by pimterry** [comment]
Ah, ok. Yes, the APIs required to attach to a JVM only exist in JDK v11+ I'm afraid.

I'm not sure if you're familiar with how externally attaching Java agents works, but there's two parts: a JVM process that starts and then attaches to a target process, and the agent code that runs inside the target process. The v11+ requirement is only for the former attaching process, so it is possible to use a v11+ JVM to attach to a v8 JVM, and interception will then work just fine.

It's also possible to intercept Java without externally attaching at all, by launching the process from intercepted terminal (where the JAVA_TOOL_OPTIONS env var is used to inject the agent at startup instead).

I think this means your options are:

* Configure a JDK v11+ version of Java either in your PATH or pointed to by your JAVA_HOME, and then use the HTTP Toolkit features like normal.
* Launch HTTP Toolkit with JAVA_HOME overridden in its environment, pointing that towards an appropriate Java version, so it can work as normal with no global changes to your environment required.
* Launch an intercepted terminal from HTTP Toolkit, and then start your target Java process from there directly, where it will be automatically intercepted via the JAVA_TOOL_OPTIONS env var even if you only have v8 installed on your system. 

(Actually looking at this right now, I think v9 _should_ work, but I've previously documented v11, so that's certainly the level where I'd expect attachment will _definitely_ work).

**Comment by sergey-prosvirnin** [comment]
Thank you first advice helped me!

**Comment by pimterry** [comment]
Great! Glad I could help :smiley:
