### ISSUE TITLE
Which versions of the JDK do you support for attach?

### ISSUE THREAD

**Issue by skanga** [httptoolkit/httptoolkit#152]
This is what I see when I try to attach to Tomcat running on JDK7

```
Exception in thread "Attach Listener" java.lang.UnsupportedClassVersionError: tech/httptoolkit/javaagent/HttpProxyAgent : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:72)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:356)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:407)
Agent failed to start!
```

**Comment by pimterry** [comment]
Hi @skanga, good question! Attachment works using https://github.com/httptoolkit/jvm-http-proxy-agent. As you've found though, that won't work on JDK 7 right now. That's built targetting Java 8+ JVMs, although some of the remote attachment APIs actually require Java 9 I think (i.e. you can intercept Java 8 in a terminal at launch, but you might need Java 9+ in your PATH to attach to running Java 8 processes in some configurations).

If you want to play around with it and see if it's possible to support JDK 7 though, do feel free! I'm not aware of any specific blockers to supporting that - it's purely that the audience for Java < 7 was so small that I haven't investigated it. If you can test it and show that that's possible, than I'd happily accept a PR to support it.

**Comment by pimterry** [comment]
Yes, that makes sense, sorry for the hassle - I've now [added this to the docs](https://github.com/httptoolkit/httptoolkit.tech/commit/bebbe08858677cc1c8fe4f54193616e872fab090).

Given that I'm going to close this issue for now, but if anybody is interested in JVM 7 or earlier support then PRs to https://github.com/httptoolkit/jvm-http-proxy-agent are very welcome!
