### ISSUE TITLE
fails to attach on java 17: Unsupported class file major version 61

### ISSUE THREAD

**Issue by maxandersen** [httptoolkit/httptoolkit#215]
when using HTTP toolkit to attach a JVM that runs java 17 it fails with the error:

```
Error configuring proxy hooks for java.net.URL:
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:10)
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:2)
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:1)
	at tech.httptoolkit.relocated.net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:359)
	at tech.httptoolkit.relocated.net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1)
	at tech.httptoolkit.relocated.net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:3)
	at tech.httptoolkit.relocated.net.bytebuddy.pool.TypePool$AbstractBase$Hierarchical.describe(TypePool.java:24)
	at tech.httptoolkit.relocated.net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:5)
	at tech.httptoolkit.relocated.net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw$RawAnnotatedType.of(TypePool.java:6)
```

**Comment by pimterry** [comment]
Thanks for reporting this @maxandersen! I think with @kamko's help I've now got a JVM agent that should work for Java 17. That'll be enabled in the next server release, which I think will probably be early in the new year now.

If you'd like to test this in the meantime, you can download the latest agent jar (v1.1.2) directly from here: https://github.com/httptoolkit/jvm-http-proxy-agent/releases. You just need to replace HTTP Toolkit's own bundled agent with that version. You can see the path to the bundled agent on your machine by looking at the `JAVA_TOOL_OPTIONS` env var in an intercepted terminal. If you replace that, everything should start working immediately.

Thanks again for reporting this, do let me know if you hit any other issues. I'll leave this issue open for now until the server release goes live.

**Comment by pimterry** [comment]
This is now live in the latest HTTP Toolkit server release. HTTP Toolkit will update in the background next time it's opened, and everything should work correctly on the subsequent run. Thanks again for reporting this :+1:
