### ISSUE TITLE
[Bug]: AgentLoadException: 102 when attaching to a jvm process

### ISSUE THREAD

**Issue by Leandro-Amorim** [httptoolkit/httptoolkit#350]
### Repro steps

I am trying to intercept a Java Web Start application and am encountering the following error:

```
Attaching agent failed
com.sun.tools.attach.AgentLoadException: 102
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:109)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:120)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:148)
	at tech.httptoolkit.javaagent.AttachMain.attachAgent(AttachMain.kt:94)
	at tech.httptoolkit.javaagent.AttachMain.main(AttachMain.kt:52)

Error: Failed to attach to JVM, exit code 3
    at A.JvmInterceptor.activate (C:\Users\Leandro\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:1287:472912)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.activateInterceptor (C:\Users\Leandro\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:1279:904)
    at async C:\Users\Leandro\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:524:4253
INFO: Activation result {"activateInterceptor":{"success":false}}
ERROR: Uncaught (in promise) Error: Failed to activate interceptor attach-jvm
ERROR: Uncaught (in promise) Error: Failed to activate interceptor attach-jvm
```

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

**Comment by pimterry** [comment]
Java Web Start is not well supported yet I'm afraid, but it is possible.

The problem is that Java interception works using a Java agent (code [here](https://github.com/httptoolkit/jvm-http-proxy-agent/)) which assumes some things about the security policy in the app it attaches too - most notably it needs to be able to read some HTTP Toolkit config from the filesystem, which isn't possible from Java Web Start.

This means that to intercept a JWS app, you'll need to download the JNLP and run it directly from an intercepted terminal with some manual configuration, rather than trying to attach to it elsewhere. You can do that by:

* Downloading the app JNLP file
* Opening an intercepted terminal via HTTP Toolkit
* Getting the path to HTTP Toolkit's Java Agent, by looking at the `JAVA_TOOL_OPTIONS` env var in that terminal
* Creating a Java policy file, e.g. `htk.policy`, containing:
  ```
  grant codebase "file:/path/to/your/java-agent.jar" {
    permission java.security.AllPermission;
  };
  ```
  (using the path from the previous step)
* Launching the app with `javaws -J-Djava.security.policy=/path/to/htk.policy target.jnlp`

The starts the app using Java Web Start as normal, but with extra permissions provided to HTTP Toolkit's agent so that it can access the files & configuration required. I've never used JWS myself, I'm not an expert on this, but I've worked out the above with some others users hitting the same issue and it seems to work.

Does that make sense? Give that a go and let me know if it works for you.

**Comment by JeremieBergeron** [comment]
@pimterry I tried what you said.
I am under windows. When I press on ``Fresh Terminal``, it open me a mingw terminal.

Here is my ``htk.policy`` file (I also try replace the path in posix):
```
grant codebase "file:C:\Users\Admin\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\overrides\java-agent.jar" {
  permission java.security.AllPermission;
};
```

Then, I run that command
```
$ javaws -J-Djava.security.policy=htk.policy my_file.jnlp

jerem@LAPTOP-BLB0QEGP MINGW64 ~/Desktop
$ java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\Admin\AppData\Local\httptoolkit\Config\ca.pem" "read")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkRead(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at tech.httptoolkit.javaagent.CustomSslContextKt.buildTrustManagerFactoryForCertificate(CustomSslContext.kt:14)
        at tech.httptoolkit.javaagent.HttpProxyAgent.interceptAllHttps(AgentMain.kt:70)
        at tech.httptoolkit.javaagent.HttpProxyAgent.premain(AgentMain.kt:47)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Picked up JAVA_TOOL_OPTIONS: -javaagent:"C:\Users\Admin\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\overrides\java-agent.jar"=127.0.0.1|8000|C:\Users\Admin\AppData\Local\httptoolkit\Config\ca.pem
Exception in thread "main"
```

I don't know why it happen. I launch the terminal in administrator AND httptoolkit in administrator

**Comment by pimterry** [comment]
@JeremieBergeron, what happens if you put the full path to the JAR in the policy file, instead of just the directory? I.e. adding `/java-agent.jar` to the end. I think forward slashes (posix format) is indeed correct.

**Comment by JeremieBergeron** [comment]
Same problem

**Comment by pimterry** [comment]
Hmmm, not sure, something must be stopping those permissions applying correctly. It looks like you might be able to enable Java security policy logging to see what's going on: https://docs.oracle.com/javase/7/docs/technotes/guides/security/troubleshooting-security.html

**Comment by JeremieBergeron** [comment]
I just realised that if I run ``javaws -J-Djava.security.policy=/path/to/htk.policy target.jnlp`` without httptoolkt, I receive this error:

```
java.net.UnknownHostException: CheminotJWS.etsmtl.ca
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.sun.deploy.net.HttpUtils.followRedirects(Unknown Source)
	at com.sun.deploy.net.BasicHttpRequest.doRequest(Unknown Source)
	at com.sun.deploy.net.BasicHttpRequest.doGetRequestEX(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.checkUpdateAvailable(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.isUpdateAvailable(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

PS: CheminotJWS is the name of the java application

**Comment by JeremieBergeron** [comment]
I am not sure what you want me to do. Could you tell me which command you want me to try?

**Comment by pimterry** [comment]
I'm afraid I'm not really familiar with JavaWS or any of these security policies, so no, I can't give you any specific steps to try.

If you want to get closer to an answer here, you need to read Oracle's [troubleshooting security policy guide](https://docs.oracle.com/javase/7/docs/technotes/guides/security/troubleshooting-security.html), work out how it all works and probably read a bunch around the topic in general, and tweak the script & command to work out whether either:

1. The policy isn't being applied at all (i.e. isn't matching the JAR for some reason)
2. The policy is being applied, but it's not working for some reason.

If you can work out which it is, that should make it much clearer to you which bits need tweaking to fix the problem.
