### ISSUE TITLE
[Bug]: System certificate injection failed

### ISSUE THREAD

**Issue by hpp0hpp** [httptoolkit/httptoolkit#406]
### the log
```
Adding cert file as /data/local/tmp/4f74014f.0
Error: Timeout for ADB command su,-c,sh,/data/local/tmp/htk-inject-system-cert.sh
    at C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:928:15455
    at async A.injectSystemCertificate (C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:928:19101)
    at async A.AndroidAdbInterceptor.injectSystemCertIfPossible (C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:928:23618)
    at async A.AndroidAdbInterceptor.activate (C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:928:20903)
    at async Object.activateInterceptor (C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:928:929)
    at async C:\Users\hpp0h\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:874323
Error reporting timed out
```

### the environment 
```
1|alioth:/ $ su root whoami
su: root: No such file or directory
127|alioth:/ $ su -c whoami
root
alioth:/ $ whoami
shell
alioth:/ $ su
alioth:/ # ls /data/local/tmp/
4f74014f.0  frida-server-16.0.2-android-arm64  hluda-server               re.frida.server
IOserver    hf-server                          htk-inject-system-cert.sh  sky.com.example.fuerdai.sha1
alioth:/ # ls /system/etc/security/cacerts/
01419da9.0  2add47b6.0  3e7271e8.0  6187b673.0  869fbf79.0  9f533518.0  b936d1c6.0  d0cddf45.0  e8651083.0
04f60c28.0  2d9dafe4.0  40dc992e.0  63a2c897.0  882de061.0  a2c66da8.0  bc3f2570.0  d16a5865.0  ed39abd0.0
0d69c7e1.0  2fa87019.0  455f1b52.0  69105f4f.0  88950faa.0  a3896b44.0  bd43e1dd.0  d18e9066.0  edcbddb5.0
10531352.0  302904dd.0  48a195d8.0  6b03dec0.0  89c02a45.0  a7605362.0  bdacca6f.0  d39b0a2c.0  f013ecaf.0
111e6273.0  304d27c3.0  4be590e0.0  75680d2e.0  8d6437c3.0  a81e292b.0  bf64f35b.0  d41b5e2a.0  f0cd152c.0
12d55845.0  31188b5e.0  5046c355.0  76579174.0  9282e51c.0  a9d40e02.0  c2c1704e.0  d4c339cb.0  f459871d.0
1ae85e5e.0  33ee480d.0  524d9b43.0  7892ad52.0  9339512a.0  ab5346f4.0  c491639e.0  d59297b8.0  fb5fa911.0
1df5a75f.0  343eb6cb.0  52b525c7.0  7a7c655d.0  9479c8c3.0  ab59055e.0  c51c224c.0  d7746a63.0  fd08c599.0
1e1eab7c.0  35105088.0  583d0756.0  7a819ef2.0  9576d26b.0  aeb67534.0  c559d742.0  da7377f6.0  fde84897.0
1e8e7201.0  399e7759.0  5a250ea7.0  7c302982.0  9591a472.0  b0ed035a.0  c90bc37d.0  dbc54cab.0
1eb37bdf.0  3ad48a91.0  5a3f0ff8.0  81b9768f.0  95aff9e3.0  b0f3e76e.0  cb156124.0  dbff3a01.0
1f58a078.0  3c6676aa.0  5acf816d.0  82223c44.0  9685a493.0  b3fb433b.0  cb1c3204.0  dc99f41e.0
219d9499.0  3c860d51.0  5cf9d536.0  83e9984f.0  985c1f52.0  b74d2bd5.0  ccc52f49.0  dfc0fe80.0
23f4c490.0  3c899c73.0  5f47b495.0  85cde254.0  9aef356c.0  b7db1890.0  cf701eeb.0  e442e424.0
27af790d.0  3c9a4d3b.0  60afe812.0  86212b19.0  9d6523ce.0  b872f2b4.0  d06393bb.0  e48193cf.0
```

Then I try this.

```
alioth:/ # /data/local/tmp/htk-inject-system-cert.sh
su: /data/local/tmp/htk-inject-system-cert.sh: can't execute: Permission denied
126|alioth:/ # chmod 777 /data/local/tmp/htk-inject-system-cert.sh
alioth:/ # /data/local/tmp/htk-inject-system-cert.sh
System cert successfully injected
alioth:/ #
```

### another test

```
⚡ 🚀 adb shell "su -c sh /data/local/tmp/htk-inject-system-cert.sh"  // **this will stuck, no response** 
⚡ 🚀 adb shell "su -c /data/local/tmp/htk-inject-system-cert.sh"
su: /data/local/tmp/htk-inject-system-cert.sh: can't execute: Permission denied
⚡ 🚀 adb shell "su -c chmod 777 /data/local/tmp/htk-inject-system-cert.sh"
chmod: Need 2 arguments (see "chmod --help")  // **don't know why I have this error** , I go into shell and chmod the script. 

⚡ 🚀 adb shell "su -c sh /data/local/tmp/htk-inject-system-cert.sh" // **still stuck, no response** 
⚡ 🚀 adb shell "su -c /data/local/tmp/htk-inject-system-cert.sh" //success
System cert successfully injected
```

### How often does this bug happen?

Every time

### The desktop OS you're using

win 11

### Details of other apps/devices

Android 13

**Comment by hpp0hpp** [comment]
@pimterry 
Hi Pimterry,
![image](https://user-images.githubusercontent.com/54829297/231116310-991d500f-8115-434f-bc3d-fa5b98a4b918.png)
this command works.

I am using powershell on windows terminal.

The device is Redmi K40 Alioth, rooted with kernelSU(not magisk)
https://github.com/tiann/KernelSU

Thank you for explain this, now I understand. Hope this can help.

**Comment by pimterry** [comment]
@hpp0hpp I think I have a fix for this. I tested quotes in general and I think it's actually correct in most cases for this command, so that's the way to go. I haven't had time to properly test the fix itself, but I think https://github.com/httptoolkit/httptoolkit-server/commit/b6a93ca56150c0c00f88ec474d3407938edf5121 should work nicely for you.

Can you test it out? To do so you'll need to stop your real HTTP Toolkit, clone that repo and run the server locally (instructions [here](https://github.com/httptoolkit/httptoolkit-server#contributing)) and then open the UI in a browser (anything but Safari will work) from [here](https://app.httptoolkit.tech).

**Comment by hpp0hpp** [comment]
@pimterry 

I tried on my phone, this is the error:
```
⚡ 🚀 npm start

> httptoolkit-server@1.12.6 start
> node-dev ./bin/run start

Config checked in 10 ms
Certificates setup in 9 ms
Standalone server started in 5 ms
Server started in 23 ms
Total startup took 47 ms
Browser cache updated
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
Webextension installed at C:\Users\hpp0h\AppData\Local\Temp\httptoolkit-webextension
httptoolkit-server: Updating CLI... not updatable
Adding cert file as /data/local/tmp/4f74014f.0
su: sh /data/local/tmp/htk-inject-system-cert.sh: inaccessible or not found

Cert injected
su: sh /data/local/tmp/htk-set-chrome-flags.sh: inaccessible or not found

Android Chrome flags set
httptoolkit-server: Updating CLI... not updatable
```

Then I tried on another phone, still an error
```
⚡ 🚀 npm start

> httptoolkit-server@1.12.6 start
> node-dev ./bin/run start

Config checked in 10 ms
Certificates setup in 9 ms
Standalone server started in 5 ms
Server started in 23 ms
Total startup took 47 ms
Browser cache updated
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
Webextension installed at C:\Users\hpp0h\AppData\Local\Temp\httptoolkit-webextension
httptoolkit-server: Updating CLI... not updatable
Adding cert file as /data/local/tmp/4f74014f.0
su: sh /data/local/tmp/htk-inject-system-cert.sh: inaccessible or not found

Cert injected
su: sh /data/local/tmp/htk-set-chrome-flags.sh: inaccessible or not found

Android Chrome flags set
httptoolkit-server: Updating CLI... not updatable

```

**Comment by pimterry** [comment]
Sorry for the delay - it took a while, but I've now significantly extended the ADB setup around this, so it should cover a lot more cases, with more detailed fallback & logging. Next time you run HTTP Toolkit, it'll update in the background, and the following time (hopefully) this should work! You can check the version you're running by hovering over the HTTP logo in the top left - the latest release with the new improvements is server v1.12.7.

If you're still having issues do please share them here.
