### ISSUE TITLE
[Bug]: docker in a fresh or attached terminal doesn't work

### ISSUE THREAD

**Issue by Niek** [httptoolkit/httptoolkit#423]
### Repro steps

1. Open HTTP Toolkit
2. Open a fresh terminal *or* attach to an existing one using `eval "$(curl -sS localhost:8001/setup)"`
3. Confirm that `curl https://amiusing.httptoolkit.tech/` works, however any docker command like `docker run curlimages/curl https://amiusing.httptoolkit.tech/` hangs

### How often does this bug happen?

Every time

### The desktop OS you're using

macOS 13.4

### Details of other apps/devices

```
$ docker --version
Docker version 23.0.5, build bc4487a
```

HTTP Toolkit `Version 1.12.6 (1.12.6)`

### Error screenshot

<img width="1124" alt="Screenshot 2023-05-22 at 16 31 28" src="https://github.com/httptoolkit/httptoolkit/assets/213140/152d3da4-1486-4cf9-b2c7-67d948f69c9e">

**Comment by Niek** [comment]
Things I have tried so far:
* Use arm64 image for `docker-socks-tunnel`: no difference
* Disable experimental and beta docker features: no difference
* Read the [Daemon logs](https://docs.docker.com/config/daemon/logs/): nothing noteworthy

**Comment by Niek** [comment]
Running `docker info` works fine in an intercepted terminal. Reading the HTTP Toolkit logs is the first thing I should have done 😄  Here is the output:
```
--- Launching HTTP Toolkit desktop v1.12.6 ---
(node:14535) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 15 ms
Certificates setup in 9 ms
Standalone server started in 7 ms
Server started in 28 ms
Total startup took 59 ms
(node:14535) Warning: Using insecure HTTP parsing
INFO: Initialising UI (version 3f058086946e6a3a852628a648c38061698391d5)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
Mock session started, http on port 8000, webrtc enabled
Updating all Docker network aliases...
Connected to Docker
Webextension installed at /var/folders/xl/bv0rcr_n7zd7d4w995sxk9w00000gn/T/httptoolkit-webextension
Docker injection volume setup error, cleaning up...
Could not start Docker components: Error: (HTTP code 502) unexpected - Bad response from Docker engine
 
    at /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:2:578499
    at IncomingMessage.<anonymous> (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:2:578437)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: undefined,
  statusCode: 502,
  json: null
}
INFO: API store initialized
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.12.6)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.6
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.6
INFO: Previous server version was 1.12.6
Starting Docker tunnel...
Updating Docker aliases for network ebc4ab5618403207f07a08db1c107b54c972fccd3b8d0cb420e4b6b30ae08ade...
Querying Docker tunnel port...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: (HTTP code 502) unexpected - Bad response from Docker engine
 
    at /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:2:578499
    at IncomingMessage.<anonymous> (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:2:578437)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Looks like this could be some incompatibility with the Docker version I'm using (`23.0.5`)?

**Comment by Niek** [comment]
Thanks for the debugging steps!

There is definitely no volume created, `docker volume ls` does not show the volume. The rest of the commands isn't showing anything either - the only container running is `httptoolkit/docker-socks-tunnel:v1.1.0`.

I see the dockerode dependency is 3.3.1 which is 2 years old - it might be worth it bumping that to 3.3.5.

**Comment by pimterry** [comment]
Hmm, OK. There's nothing obviously likely to fail before that point AFAICT, so volume creation does seem most likely to be the cause. That's very odd, I don't know any good reasons why we wouldn't be able to create a volume! I can't see anything obvious in the [recent changes](https://github.com/apocas/dockerode/compare/v3.3.1...master) in Dockerode that would affect this either.

I'm not next to the M1 Mac I use for testing right now, but I will be tomorrow - I'll update to the latest Docker and see if I can reproduce this for myself there. It's certainly worked there in the past, so it's either a recent update or some other difference in the configuration with your machine. If there's anything unusual about your setup you can think of that could be related to this, do let me know :smile:

**Comment by Niek** [comment]
I got a bit further, I was actually looking at the wrong Docker logs (the interesting stuff is in `~/Library/Containers/com.docker.docker/Data/log/vm/dockerd.log`). Here is the output that I see when loading HTTP Toolkit:
```
[2023-05-23T19:47:42.655388587Z][dockerd][I] time="2023-05-23T19:47:42.652914670Z" level=debug msg="Calling GET /_ping"
[2023-05-23T19:47:42.666882670Z][dockerd][I] time="2023-05-23T19:47:42.653198420Z" level=debug msg="Calling GET /_ping"
[2023-05-23T19:47:42.679925837Z][dockerd][I] time="2023-05-23T19:47:42.679814712Z" level=debug msg="Calling GET /events"
[2023-05-23T19:47:42.680509587Z][dockerd][I] time="2023-05-23T19:47:42.680394837Z" level=debug msg="Calling GET /networks"
[2023-05-23T19:47:42.681510253Z][dockerd][I] time="2023-05-23T19:47:42.681385878Z" level=debug msg="Calling GET /images/httptoolkit/docker-socks-tunnel:v1.1.0/json"
[2023-05-23T19:47:42.681694420Z][dockerd][I] time="2023-05-23T19:47:42.681614712Z" level=debug msg="Calling GET /volumes/httptoolkit-injected-data-1.12.6"
[2023-05-23T19:47:42.681766795Z][dockerd][I] time="2023-05-23T19:47:42.681695587Z" level=debug msg="Probing all drivers for volume with name: httptoolkit-injected-data-1.12.6"
[2023-05-23T19:47:42.697746545Z][dockerd][I] time="2023-05-23T19:47:42.697635337Z" level=debug msg="Calling GET /networks/e598cc28f0a14e89d6d399ac4403febf3f671e5c8c33d7fd1258f0361b76e935"
[2023-05-23T19:47:42.698796712Z][dockerd][I] time="2023-05-23T19:47:42.698735128Z" level=debug msg="Calling GET /networks/e7ab36dcf21e5ba85ed6300fb739af8e2064bda952dc6dc15d8471e869d8bdcc"
[2023-05-23T19:47:42.699105212Z][dockerd][I] time="2023-05-23T19:47:42.699002712Z" level=debug msg="Calling GET /networks/fe3049c0e8928913d3926581fa1c47ef9debbbf90c7d926039991d0029d6d199"
[2023-05-23T19:47:42.699949420Z][dockerd][I] time="2023-05-23T19:47:42.699882378Z" level=debug msg="Calling GET /networks/ebdac665769a4261b7e43c32b5a551b56ab2e4be9fe6633a6b75a13933b7f5eb"
[2023-05-23T19:47:42.700361962Z][dockerd][I] time="2023-05-23T19:47:42.700298378Z" level=debug msg="Calling GET /containers/json?all=true&filters=%7B%22label%22%3A%5B%22tech.httptoolkit.docker.scratch%22%5D%7D"
[2023-05-23T19:47:42.701287087Z][dockerd][I] time="2023-05-23T19:47:42.701165712Z" level=debug msg="Calling GET /networks/473cc81d50816febf5e8396a39e467ab6fcca4fab763394f4e14bda49ab75f45"
[2023-05-23T19:47:42.716121337Z][dockerd][I] time="2023-05-23T19:47:42.716023545Z" level=debug msg="Calling GET /images/json?filters=%7B%22label%22%3A%5B%22tech.httptoolkit.docker.scratch%22%5D%7D"
[2023-05-23T19:47:42.730923962Z][dockerd][I] time="2023-05-23T19:47:42.730856295Z" level=debug msg="encountered unknown type application/vnd.in-toto+json; children may not be fetched"
[2023-05-23T19:47:42.755575462Z][dockerd][I] time="2023-05-23T19:47:42.755442295Z" level=debug msg="Calling GET /images/httptoolkit/scratch/json"
[2023-05-23T19:47:42.755658378Z][dockerd][I] time="2023-05-23T19:47:42.755457962Z" level=debug msg="Calling POST /volumes/create?Name=httptoolkit-injected-data-1.12.6&Labels=%7B%22tech.httptoolkit.docker.data-volume%22%3A%221.12.6%22%2C%22tech.httptoolkit.docker.data-volume.cert-content%22%3A%22-----BEGIN%20CERTIFICATE-----%5Cr%5CnMIIDTzCCAjegAwIBAgIRCnXeT%2BxlfU24oSyH1MVhwygwDQYJKoZIhvcNAQELBQAw%5Cr%5CnQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYGA1UE%5Cr%5CnChMPSFRUUCBUb29sa2l0IENBMB4XDTIzMDUyMTEzMjk0OVoXDTI0MDUyMjEzMjk0%5Cr%5CnOVowQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYG%5Cr%5CnA1UEChMPSFRUUCBUb29sa2l0IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB%5Cr%5CnCgKCAQEA6oscOLq4b0jD48BDN8jbUtX3wS%2BofIjaXDhqM41UZAFHvtalzGnD3AC1%5Cr%5CnQMGaPRUOCQGsP0rgmOZI5yLuFtHlqOFMLzgZ5fAgbrpYpgw9lug3bjUIFc7NqtdA%5Cr%5CnzF8Ok5MO0DvzMApcDMsv11EbaABVqAxldTobTWYkKzO49ItVHo08ddyFYGn6plbi%5Cr%5Cn4dAItKbg8FGiZBoCSjKp73wWaFkqNvebyKLfwNoCzE4Li2SJ34F7wKi5JwfRPpG6%5Cr%5Cn8czCsb0n356INUNQFA6t%2BCJvzLr2rulnp3gOvgrNM3jnPNTWCbNXNm2CseB06sbH%5Cr%5CnCzdknE0YNI
[2023-05-23T19:47:42.755934045Z][dockerd][I] time="2023-05-23T19:47:42.755702128Z" level=debug msg="form data: {\"Labels\":{\"tech.httptoolkit.docker.data-volume\":\"1.12.6\",\"tech.httptoolkit.docker.data-volume.cert-content\":\"-----BEGIN CERTIFICATE-----\\r\\nMIIDTzCCAjegAwIBAgIRCnXeT+xlfU24oSyH1MVhwygwDQYJKoZIhvcNAQELBQAw\\r\\nQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYGA1UE\\r\\nChMPSFRUUCBUb29sa2l0IENBMB4XDTIzMDUyMTEzMjk0OVoXDTI0MDUyMjEzMjk0\\r\\nOVowQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYG\\r\\nA1UEChMPSFRUUCBUb29sa2l0IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\\r\\nCgKCAQEA6oscOLq4b0jD48BDN8jbUtX3wS+ofIjaXDhqM41UZAFHvtalzGnD3AC1\\r\\nQMGaPRUOCQGsP0rgmOZI5yLuFtHlqOFMLzgZ5fAgbrpYpgw9lug3bjUIFc7NqtdA\\r\\nzF8Ok5MO0DvzMApcDMsv11EbaABVqAxldTobTWYkKzO49ItVHo08ddyFYGn6plbi\\r\\n4dAItKbg8FGiZBoCSjKp73wWaFkqNvebyKLfwNoCzE4Li2SJ34F7wKi5JwfRPpG6\\r\\n8czCsb0n356INUNQFA6t+CJvzLr2rulnp3gOvgrNM3jnPNTWCbNXNm2CseB06sbH\\r\\nCzdknE0YNIhPhDY5nImef/utQJyQfwIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/\\r\\nMA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU
[2023-05-23T19:47:42.755945587Z][dockerd][I] time="2023-05-23T19:47:42.755785462Z" level=debug msg="using regular volume"
[2023-05-23T19:47:42.755971795Z][dockerd][I] time="2023-05-23T19:47:42.755875503Z" level=debug msg="Probing all drivers for volume with name: httptoolkit-injected-data-1.12.6"
[2023-05-23T19:47:42.755972295Z][dockerd][I] time="2023-05-23T19:47:42.755954712Z" level=debug msg="Registering new volume reference: driver \"local\", name \"httptoolkit-injected-data-1.12.6\""
[2023-05-23T19:47:42.778292253Z][dockerd][I] time="2023-05-23T19:47:42.778167503Z" level=debug msg="Calling POST /build?dockerfile=Dockerfile&t=httptoolkit%2Fscratch&labels=%7B%22tech.httptoolkit.docker.scratch%22%3A%22%22%7D"
[2023-05-23T19:47:42.781333462Z][dockerd][I] 2023/05/23 19:47:42 http: panic serving @: not implemented
[2023-05-23T19:47:42.781342670Z][dockerd][I] goroutine 236968 [running]:
[2023-05-23T19:47:42.781352253Z][dockerd][I] net/http.(*conn).serve.func1()
[2023-05-23T19:47:42.781352503Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:1854 +0xb0
[2023-05-23T19:47:42.781355253Z][dockerd][I] panic({0x1ce2320, 0x24df2d0})
[2023-05-23T19:47:42.781355420Z][dockerd][I] 	/usr/local/go/src/runtime/panic.go:890 +0x248
[2023-05-23T19:47:42.781358253Z][dockerd][I] github.com/docker/docker/daemon/containerd.(*ImageService).MakeImageCache(0x40018d4c08?, {0x1232348?, 0x30?}, {0x1ef3460?, 0x40018d4c01?, 0x51c890?})
[2023-05-23T19:47:42.781358795Z][dockerd][I] 	/go/src/github.com/docker/docker/daemon/containerd/cache.go:11 +0x2c
[2023-05-23T19:47:42.781367712Z][dockerd][I] github.com/docker/docker/builder/dockerfile.newImageProber.func1(...)
[2023-05-23T19:47:42.781367878Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/imageprobe.go:32
[2023-05-23T19:47:42.781370212Z][dockerd][I] github.com/docker/docker/builder/dockerfile.newImageProber({0x2504e98, 0x4001b1b3b0}, {0xffff5c1ab298?, 0x4000aa5350}, {0x0?, 0x0, 0x0}, 0x0?)
[2023-05-23T19:47:42.781370837Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/imageprobe.go:35 +0xe4
[2023-05-23T19:47:42.781373378Z][dockerd][I] github.com/docker/docker/builder/dockerfile.newBuilder({0x2504e98, 0x4001b1b3b0}, {0x40008ab180, {0x25161b0, 0x4000aa5350}, {{0x24e10c0, 0x4001ae55f0}, {0x24e1d40, 0x4001ae5608}, {0x24e1d40, ...}, ...}, ...})
[2023-05-23T19:47:42.781373878Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:138 +0x88
[2023-05-23T19:47:42.781376378Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*BuildManager).Build(0x4000bf7b30, {0x2504f40, 0x4001b22c30}, {{0x24ee0d8, 0x4001b22cc0}, {{0x24e10c0, 0x4001ae55f0}, {0x24e1d40, 0x4001ae5608}, {0x24e1d40, ...}, ...}, ...})
[2023-05-23T19:47:42.781376753Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:94 +0x214
[2023-05-23T19:47:42.781396545Z][dockerd][I] github.com/docker/docker/api/server/backend/build.(*Backend).Build(0x4000e0a060, {0x2504f40, 0x4001b22c30}, {{0x24ee0d8, 0x4001b22cc0}, {{0x24e10c0, 0x4001ae55f0}, {0x24e1d40, 0x4001ae5608}, {0x24e1d40, ...}, ...}, ...})
[2023-05-23T19:47:42.781396795Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/backend/build/backend.go:69 +0x154
[2023-05-23T19:47:42.781399378Z][dockerd][I] github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0x4000e0e000, {0x2504f40, 0x4001b22c30}, {0x2503820, 0x4000d23500}, 0x40018f2a00, 0xffff5c2d0d01?)
[2023-05-23T19:47:42.781399920Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/router/build/build_routes.go:280 +0x5d0
[2023-05-23T19:47:42.781402462Z][dockerd][I] github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1({0x2504f40, 0x4001b22c30}, {0x2503820?, 0x4000d23500?}, 0x1ce2320?, 0x4001339590?)
```

The `http: panic serving @` is strange, like it's missing an IP/port?

**Comment by pimterry** [comment]
Yes, that'll definitely be the cause! Very odd. The `http: panic serving @:` appears to be Go's HTTP server's standard error format, and I expect the missing address is because it's listening on a unix socket (`/var/run/docker.sock`) rather than an actual network address.

The `not implemented` is indeed the interesting part. The request to create the volume looks reasonable to me, I have no idea where `not implemented` would come from here! There is a little noise because the from-scratch blank image build also happens in parallel at the same time here, but it appears to succeed happily afterwards so I assume that's not related.

I've dug through every reference to `not implemented` (lowercase, without any prefix/suffix) in the Docker Engine itself: https://github.com/search?q=repo%3Adocker%2Fengine+%22not+implemented%22&type=code. There's not actually that many - at least half the results there aren't lowercase or include some extra context in the message. Most of the possibilities seem to relate to network drivers that don't support specific features. Are you using any custom drivers? Storage drivers especially could cause this.

What happens if you run the equivalent Docker volume commands manually?

It would be interesting to confirm that `docker volume create` works at all, for starters.

Assuming it does, you can reproduce the full equivalent command with something like:

```
docker volume create "httptoolkit-injected-data-1.12.6" \
    --label "tech.httptoolkit.docker.data-volume=1.12.6" \
    --label "tech.httptoolkit.docker.data-volume.cert-content=-----BEGIN%20CERTIFICATE-----%5Cr%5CnMIIDTzCCAjegAwIBAgIRCnXeT%2BxlfU24oSyH1MVhwygwDQYJKoZIhvcNAQELBQAw%5Cr%5CnQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYGA1UE%5Cr%5CnChMPSFRUUCBUb29sa2l0IENBMB4XDTIzMDUyMTEzMjk0OVoXDTI0MDUyMjEzMjk0%5Cr%5CnOVowQTEYMBYGA1UEAxMPSFRUUCBUb29sa2l0IENBMQswCQYDVQQGEwJYWDEYMBYG%5Cr%5CnA1UEChMPSFRUUCBUb29sa2l0IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB%5Cr%5CnCgKCAQEA6oscOLq4b0jD48BDN8jbUtX3wS%2BofIjaXDhqM41UZAFHvtalzGnD3AC1%5Cr%5CnQMGaPRUOCQGsP0rgmOZI5yLuFtHlqOFMLzgZ5fAgbrpYpgw9lug3bjUIFc7NqtdA%5Cr%5CnzF8Ok5MO0DvzMApcDMsv11EbaABVqAxldTobTWYkKzO49ItVHo08ddyFYGn6plbi%5Cr%5Cn4dAItKbg8FGiZBoCSjKp73wWaFkqNvebyKLfwNoCzE4Li2SJ34F7wKi5JwfRPpG6%5Cr%5Cn8czCsb0n356INUNQFA6t%2BCJvzLr2rulnp3gOvgrNM3jnPNTWCbNXNm2CseB06sbH%5Cr%5CnCzdknE0YNI"
```

I've just copied the encoded cert here - shouldn't make any difference, but you could read the full content of your CA cert directly, if you wanted to make this a properly accurate test.

Maybe it's the length of that label? I've never seen issues there and I wasn't aware of any kind of length limit on label strings, but that's really the only unusual thing that's going on here AFAICT.

**Comment by Niek** [comment]
I just noticed the POST request in the logs is not complete, because the debug logs are truncated :( See also: https://github.com/docker/for-mac/issues/6037

**Comment by pimterry** [comment]
> Looking at the logs it seems that creating the volume itself is not really the problem, but the step calling /build. 

Ah yes, you're totally right, I'd interpreted that as being more log lines, but it's a stacktrace of some sort, you're quite right.

From that stacktrace, it seems it's setting up an image cache (so it's presumably still preparing to start the build). The last steps are [newBuilder](https://github.com/moby/moby/blob/c5126d1435363c5ffbe81ffe7e70734513aaa17f/builder/dockerfile/builder.go#L132) preparing to start a build, running [newImageProber](https://github.com/moby/moby/blob/c5126d1435363c5ffbe81ffe7e70734513aaa17f/builder/dockerfile/imageprobe.go#L26) which calls [MakeImageCache](https://github.com/moby/moby/blob/c5126d1435363c5ffbe81ffe7e70734513aaa17f/daemon/containerd/cache.go#L15), and that then panicking somehow. I'm not really familiar with Go, and I have no idea why that'd happen in the code there, but that's my best understanding.

> If I try to replicate that in curl, I get a different error:...

> I just noticed the POST request in the logs is not complete, because the debug logs are truncated :(

Even if this wasn't, sending this request is harder than it looks. The build command isn't just a simple request, it includes the entire Docker context of files to build as a raw tarball stream, sent in the request body. It's not an easily readable string. It's possible to send a build request with curl, but it'll be a bit tricky. If you want more context, the API docs for the /build endpoint are here: https://docs.docker.com/engine/api/v1.43/#tag/Image/operation/ImageBuild.

You can probably reproduce it with the Docker CLI though. The build ([here](https://github.com/httptoolkit/httptoolkit-server/blob/9b62da64806f8149f838509f8d2d6244b66496b5/src/interceptors/docker/docker-data-injection.ts#L69-L92C2)) is approximately equivalent to running `DOCKER_BUILDKIT=0 docker build .` (i.e. doing a simple build, without BuildKit) within a directory containing just a single `Dockerfile`, that contains:

```
FROM scratch
ENTRYPOINT ["FAIL"]
```

It builds a completely empty image, which is never actually intended to be run.

If you create that file in an empty directory, then go there and run that command, does it build for you?

One thing we could do is to set `nocache` for this build, which would skip that step. That would definitely avoid _this_ panic, but I think it would be better to work out why this is panicking, because I suspect if we merely dodge this error than it'll just break somewhere further down the line.

**Comment by pimterry** [comment]
If you build with `DOCKER_BUILDKIT=0 docker build . --no-cache`, does it work correctly?

What about if you run `docker builder prune -a` (this will clear your Docker build cache) and then run the same command as before? I.e. without using `--no-cache`.

There must be something strange happening in the build cache on your system, but I have no idea what it is. Non-BuildKit builds are deprecated nowadays, but they were the standard for a very long time and they're extremely widely used and certainly haven't been removed _yet_, so they should definitely still work.

**Comment by pimterry** [comment]
> Seems like I should open an issue on the Docker repo?

Yes, good plan. At this point it's reproducible standalone with what should be a trivial Dockerfile & basic commands, it's definitely a bug. Would be nice to find a workaround of course, but regardless it's worth reporting it to get that fixed properly.

**Comment by Niek** [comment]
Thanks, opened an issue here: https://github.com/docker/for-mac/issues/6853

**Comment by Niek** [comment]
@pimterry Unfortunately not - still the same issue on my end with hanging `docker run` commands.

**Comment by pimterry** [comment]
Ok, I think this should now be really _really_ fixed on the Docker side - that separate bug (https://github.com/moby/moby/issues/46248) with `FROM scratch` has since been fixed (https://github.com/moby/moby/pull/46284) and this fix is released, so everything should work correctly in Docker desktop 4.23.0+ / Docker engine 24.0.6+, I think.

I'm going to close this for now as done. If you're still seeing this, let me know and I'm happy to investigate further, but fingers crossed that is all sorted. And we managed to find and get fixed multiple new bugs in Docker itself en route, great result!

**Comment by Niek** [comment]
Thanks @pimterry! I upgraded Docker desktop to the latest version, and I can confirm everything is working as expected now.
