### ISSUE TITLE
[Bug]: Bluestacks can't find su

### ISSUE THREAD

**Issue by hendrix04** [httptoolkit/httptoolkit#441]
### Repro steps

Use https://bstweaker.tk/ to root Bluestacks 5.9 (Android Pie image)
Connect to Android with HTTP Toolkit
Logs show "returned `/system/bin/sh: su: not found`"

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Any other info?

I logged into the shell and did a "which su" and it shows that the location is /system/xbin/su

Logs:
```
--- Launching HTTP Toolkit desktop v1.12.8 ---
INFO: Initialising UI (version 1daef1176df850437cb1c4942e5b47ebb4056c8e)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
(node:180320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 12 ms
INFO: Server initialization failed TypeError: Failed to fetch
Certificates setup in 101 ms
Standalone server started in 6 ms
Server started in 16 ms
Total startup took 136 ms
(node:180320) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.12.9)
INFO: Rules store initialized
INFO: Events store initialized
Webextension installed at C:\Users\hendrix\AppData\Local\Temp\httptoolkit-webextension
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
INFO: Service worker loaded
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
Browser cache updated
INFO: Previous server version was null
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `/system/bin/sh: su: not found`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `/system/bin/sh: su: not found`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `/system/bin/sh: su: not found`
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] returned `/system/bin/sh: su: not found`
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Error
    at C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:45821
    at s (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:410956)
    at N._settlePromiseFromHandler (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:381463)
    at N._settlePromise (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:382263)
    at N._settlePromise0 (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:382962)
    at N._settlePromises (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:384314)
    at s (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:329161)
    at o (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:329100)
    at a._drainQueues (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:330226)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\hendrix\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:2:329034)
    at processImmediate (node:internal/timers:466:21)
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Root not available, skipping cert injection
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
App not installed, installing...
Streaming remote APK directly
Updating local APK to version v1.3.7
Local APK written to C:\Users\hendrix\AppData\Local\Temp\tmp-180320toTD3CYaInjK.tmp
Local APK moved to C:\Users\hendrix\AppData\Local\httptoolkit\Config\httptoolkit-v1.3.7.apk
Deleting old APKs: 
App installed successfully
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
127.0.0.1:5556 disconnected, dropping the ADB tunnel
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
Adding cert file as /data/local/tmp/4f74014f.0
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-inject-system-cert.sh' ] returned `System cert successfully injected`
System cert successfully injected

Cert injected
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed

Android command [ 'su', '-c', 'am force-stop com.android.chrome' ] returned ``
Android Chrome flags set
127.0.0.1:5556 ADB tunnel failed Failure: 'device '127.0.0.1:5556' not found'
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Adding cert file as /data/local/tmp/4f74014f.0
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-inject-system-cert.sh' ] returned `System cert successfully injected`
System cert successfully injected

Cert injected
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed

Android command [ 'su', '-c', 'am force-stop com.android.chrome' ] returned ``
Android Chrome flags set
App not installed, installing...
Streaming local APK
App installed successfully

```

**Comment by pimterry** [comment]
Hi @hendrix04. Interesting case, I haven't seen this before. Can you share your full HTTP Toolkit logs for this? It should have a bit more context on all the commands run and what happens.

HTTP Toolkit intercepts rooted devices via ADB by running a few setup commands as root. To be able to run things as root, it has to first test a few mechanisms that might provide usable root access, by injecting a tiny script containing just `whoami`, then running all the below in parallel via `adb shell`, and seeing which prints `root`:

```
sh /data/local/tmp/htk-root-test.sh
su -c 'sh /data/local/tmp/htk-root-test.sh'
su -c sh /data/local/tmp/htk-root-test.sh
su root 'sh /data/local/tmp/htk-root-test.sh'
su root sh /data/local/tmp/htk-root-test.sh
```

(Full code [here](https://github.com/httptoolkit/httptoolkit-server/blob/b7379efcde361e0ab55383eac73ee4cbd4379bcd/src/interceptors/android/adb-commands.ts#L153-L202)).

If none of those work, it runs `adb root` (restarting ADB in rooted mode, if possible) and then just running `sh /data/local/tmp/htk-root-test.sh` directly.

Do any of those work for you? If not, any idea what test command would work on this device? I'd prefer not to hardcode unusual paths if possible since they can be extremely variable between different devices and the number of commands we'd have to run could explode hugely.

**Comment by hendrix04** [comment]
@pimterry, I was just coming in to paste the full logs (now in the original post) as I have been digging around a bit more.

Those commands don't work for me as that file doesn't exist. That being said, doing 'su -c echo "hello world"' executes just fine in the terminal.

**Comment by pimterry** [comment]
The shell script is injected, it's literally just this: https://github.com/httptoolkit/httptoolkit-server/blob/b7379efcde361e0ab55383eac73ee4cbd4379bcd/src/interceptors/android/adb-commands.ts#L178-L181. If you create a file that just contains `whoami` and make it executable with `chmod +x`, that should be basically equivalent.

There's something odd happening here though, as your logs show these batches of commands being tried 3 times, and only the first time throws that error, while the 2nd & 3rd tries work correctly, and then seem to set up the device successfully. Did something changes between those tests?

**Comment by hendrix04** [comment]
Hmm, I have been playing with a lot of stuff (I lose root every time the VM reboots).

It's possible that I didn't actually have root the first time?

I see at the bottom that it does say that the system cert was injected, but the app still shows "system trust disabled".

**Comment by hendrix04** [comment]
Fresh new log. It seems like the missing su must have just been a mistake on my part.

Still trying to figure out why system trust is not working though. At least it is a different problem than the original problem.

```--- Launching HTTP Toolkit desktop v1.12.8 ---
INFO: Initialising UI (version 1daef1176df850437cb1c4942e5b47ebb4056c8e)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
(node:205308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 14 ms
Certificates setup in 7 ms
Standalone server started in 4 ms
Server started in 14 ms
Total startup took 40 ms
(node:205308) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.12.9)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
Webextension installed at C:\Users\hendrix\AppData\Local\Temp\httptoolkit-webextension
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.9
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Adding cert file as /data/local/tmp/4f74014f.0
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-inject-system-cert.sh' ] returned `System cert successfully injected`
System cert successfully injected

Cert injected
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed

Android command [ 'su', '-c', 'am force-stop com.android.chrome' ] returned ``
Android Chrome flags set
App not installed, installing...
Streaming local APK
INFO: Previous server version was 1.12.9
App installed successfully
```

**Comment by pimterry** [comment]
Hmm, OK. If you open a shell yourself once the device is set up, do you see `/system/etc/security/cacerts/4f74014f.0`? That should contain your certificate. If you run `mount`, can you see a tmpfs mount over that cacerts directory?

We have seen previous issues (https://github.com/httptoolkit/httptoolkit-android/issues/8#issuecomment-1016471036) with devices rooted via Magisk, but then that seemed to be completely resolved in more recent Magisk releases so investigation stopped. Maybe BSTweaker is using an older version of Magisk though? That would plausibly do this.

**Comment by hendrix04** [comment]
If I am logged in as root, I can see that file and that mount.

```127|z3q:/ $ su -c ls /system/etc/security/cacerts/4f7*
/system/etc/security/cacerts/4f74014f.0
z3q:/ $ ls /system/etc/security/cacerts/4f7*
ls: /system/etc/security/cacerts/4f7*: No such file or directory
1|z3q:/ $ su -c mount | grep cacerts
tmpfs on /system/etc/security/cacerts type tmpfs (rw,seclabel,relatime)
tmpfs on /system/etc/security/cacerts type tmpfs (rw,seclabel,relatime)
z3q:/ $ mount | grep cacerts```

**Comment by pimterry** [comment]
Yeah that definitely looks suspicious. The permissions might differ, but both normal users & root should still see the same thing here.

You can probably work around this by copying 4f74014f.0 to /data/local/tmp, unmounting those cacerts tmpfs mounts (I assume duplicated because HTTP Toolkit can't see the cert before it gets root either!), running `adb remount` to make /system writable, then copying the file back into the (now real and modifiable) /system/etc/security/cacerts/ directory. That will add the cert to the system permanently instead of temporarily but that's fine - HTTP Toolkit only does it temporarily to be a little tidier. Once that's done, you can check the system CA certificate list on your device (Security -> Encryption -> Trusted Credentials -> System) and HTTP Toolkit CA should appear there.

Does that work for you?

**Comment by hendrix04** [comment]
I am heading out on vacation tomorrow, but I will give this a shot when I
get back in a week.

I definitely don't mind having it installed permanently. Thanks for your
help and I will give you an update when I can.

**Comment by hendrix04** [comment]
Hmm, so I am not trying to do this via adb so idk if that makes a difference, but I get an error when I try to do `mount -o rw,remount /system`

```
mount: '/dev/sda1'->'/system': I/O error
```

**Comment by pimterry** [comment]
Hmm, I'm not sure, but I think `adb remount` and simply changing mount options do work differently, although I'm not actually sure what the mechanism is there.

I think that is the only option left though - for any Android device, you either need to be able to write to /system, or mount on top of it in a way visible to all processes, or it won't be possible to set up system certs at all.

The only 3rd possibility is the one mentioned in https://github.com/httptoolkit/httptoolkit-android/issues/8#issuecomment-1016471036 of building a custom magisk module to inject the certs, and loading that. That is a feature magisk apparently provides, but I've never tried it and it'd require a bit of R&D to build out a module that injects this correctly. If you do go down that route, please let me know how it goes! If it's not too tricky I'd love to integrate that into HTTP Toolkit to handle magisk cases like this automatically in future.
