### ISSUE TITLE
[Bug]:  Connection Aborted in some apps like blink

### ISSUE THREAD

**Issue by AbdallahAwd** [httptoolkit/httptoolkit#449]
### Repro steps

An app like Blink on Android whenever I upload a file it aborts the connection 
![image](https://github.com/httptoolkit/httptoolkit/assets/73560483/1cd2b74f-6423-4bca-aa1d-30e30bd452a9)

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows

### Details of other apps/devices

Android 13

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/73560483/2547429b-770d-4eec-9034-cd867e6e1428)

**Comment by AbdallahAwd** [comment]
this app
https://play.google.com/store/apps/details?id=com.vistring.blink.android&hl=en
I think the server it's connected to pinning the request.
![image](https://github.com/httptoolkit/httptoolkit/assets/73560483/02d6ca40-b23f-4252-9c7c-75403e702b9d)

it keeps uploading the file until aborted it. I wonder if there is any solution 
![image](https://github.com/httptoolkit/httptoolkit/assets/73560483/bc19220b-5a39-46a9-ab92-8d5e79b0f6f4)

**Comment by pimterry** [comment]
Hmm, ok. That implies there's no setup issue, and this is either due to very odd client or server behaviour or a traffic processing bug. Does this happen for all uploads, every time? Is there anything else special required to trigger this?

It would also be useful to look at the ADB logs. If you run `adb logcat -T1` and then trigger this, does anything useful appear there? Errors and stacktraces would be particularly helpful.

There may also be clues in your HTTP Toolkit logs, those are available from the menu under Help -> View HTTP Toolkit logs.

**Comment by AbdallahAwd** [comment]
Yes for all uploads.

HTTP ToolKit logs
```
--- Launching HTTP Toolkit desktop v1.12.8 ---
INFO: Initialising UI (version 96dfd11e1feac2425f685436eb2adfe70c587a5e)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Service worker loaded
(node:9608) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 27 ms
Certificates setup in 13 ms
Standalone server started in 8 ms
Server started in 21 ms
Total startup took 69 ms
(node:9608) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
httptoolkit-server: Updating CLI... fetching manifest
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.13.0)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... already on latest version: 1.13.0
Webextension installed at C:\Users\AMA\AppData\Local\Temp\httptoolkit-webextension
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.13.0
Browser cache updated
INFO: Previous server version was 1.13.0
Error: Aborted
    at IncomingMessage.a (C:\Users\AMA\AppData\Local\httptoolkit-server\client\1.13.0\bundle\index.js:890:38068)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:102:25)
    at IncomingMessage.destroy (node:internal/streams/destroy:64:5)
    at abortIncoming (node:_http_server:642:9)
    at socketOnClose (node:_http_server:636:3)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12)
    at node:net:301:12
    at Socket.done (node:_tls_wrap:588:7)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
Failed to handle request: socket hang up
```

ADB 

```
7-14 12:58:00.013  3323  3748 I AiAiEcho: EchoTargets: Feature:1
07-14 12:58:00.013  3323  3748 I AiAiEcho: Filtered by AiAi flag check:
07-14 12:58:00.013  3323  3748 I AiAiEcho: [CONTEXT ratelimit_period="10 SECONDS" ]
07-14 12:58:00.014  3323  3748 I AiAiEcho: Ranked targets strategy: WEIGHTED, count: 1, ranking metadata: { cardId: WEATHER-569377242, card type: 1, update time: 2023-07-14T10:25:35Z, expiration time: 2023-07-14T11:00:00Z, ranking metadata: RankingMetaData(urgency=0.391, priority=0.3, recency=1.0, rankScore=0.117300004, importantTimePoints=# lte@7bca4) } [CONTEXT ratelimit_period="10 SECONDS" ]
07-14 12:58:00.015  3323  3748 I AiAiEcho: #weatherTwiddler: Weather removes SubtitleSupplementalItem in surface: lockscreen [CONTEXT ratelimit_period="10 SECONDS" ]
07-14 12:58:00.018  3323  3748 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface lockscreen with targets# 1 (types=[1])
07-14 12:58:00.030  2100  2100 D SsBaseTemplateCard: No text view can be set up
07-14 12:58:00.030  2100  2100 D SsBaseTemplateCard: Passed-in item info is null
07-14 12:58:00.030  2100  2100 D SsBaseTemplateCard: Passed-in item info is null
07-14 12:58:00.030  2100  2100 I SsBaseTemplateCard: Secondary card pane is null
07-14 12:58:00.048  2351  2351 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 1
07-14 12:58:00.059  3323  3748 I AiAiEcho: Predicting[7]: { Feature:1, creation:2023-07-14T10:25:35Z, expiry:2023-07-14T11:00:00Z, isExpired: false}, { Feature:1, creation:2023-07-14T11:00:00Z, expiry:2023-07-14T11:00:00Z, isExpired: true}, { Feature:1, creation:2023-07-14T12:00:00Z, expiry:2023-07-14T12:00:00Z, isExpired: true}, { Feature:1, creation:2023-07-14T13:00:00Z, expiry:2023-07-14T13:00:00Z, isExpired: true}, { Feature:1, creation:2023-07-14T14:00:00Z, expiry:2023-07-14T14:00:00Z, isExpired: true}, { Feature:1, creation:2023-07-14T15:00:00Z, expiry:2023-07-14T15:00:00Z, isExpired: true}, { Feature:1, creation:2023-07-14T16:00:00Z, expiry:2023-07-14T16:00:00Z, isExpired: true} [CONTEXT sampling_count=5 ]
07-14 12:58:00.060  3323  3748 I AiAiEcho: EchoTargets: Feature:1
07-14 12:58:00.060  3323  3748 I AiAiEcho: Filtered by AiAi flag check:
07-14 12:58:00.060  3323  3748 I AiAiEcho: [CONTEXT ratelimit_period="10 SECONDS" ]
07-14 12:58:00.060   572   572 E SELinux : avc:  denied  { find } for interface=vendor.google.google_battery::IGoogleBattery sid=u:r:platform_app:s0:c512,c768 pid=2100 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
07-14 12:58:00.060  3323  3748 I AiAiEcho: Ranked targets strategy: WEIGHTED, count: 1, ranking metadata: { cardId: WEATHER-569377242, card type: 1, update time: 2023-07-14T10:25:35Z, expiration time: 2023-07-14T11:00:00Z, ranking metadata: RankingMetaData(urgency=0.391, priority=0.3, recency=1.0, rankScore=0.117300004, importantTimePoints=# lte@7bca4) } [CONTEXT ratelimit_period="10 SECONDS" ]
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager: failed to get Google Battery HAL:
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager: java.util.NoSuchElementException
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager:       at android.os.HwBinder.getService(Native Method)
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager:       at android.os.HwBinder.getService(HwBinder.java:81)
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager:       at vendor.google.google_battery.V1_1.IGoogleBattery.getService(Unknown Source:2)
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager:       at vendor.google.google_battery.V1_1.IGoogleBattery.getService(Unknown Source:2)
07-14 12:58:00.060  2100 17439 E AdaptiveChargingManager:       at com.google.android.systemui.googlebattery.AdaptiveChargingManager.initHalInterface(AdaptiveChargingManager.java:46)
```

**Comment by pimterry** [comment]
@alex88 do you have an easy way to reproduce requests that trigger this issue? I never managed to get the above app running on a test device in a way that I could reproduce this issue.

A simple curl command or something similar with standard tools would be super helpful to be able to explore this further.
