### ISSUE TITLE
[Bug]: Mobile app cannot process some requests when HTTP Toolkit is enabled.

### ISSUE THREAD

**Issue by MrSatisfaction** [httptoolkit/httptoolkit#456]
### Repro steps

 I have installed on my Android mobile an application whose source code has been modified in order to disable certificate pinning.

When I try to register an account on this application, the request seems to fail as the loading logo keeps spinning. Sometimes it instantly displays a simple message saying servers could not be reached and then I cannot go further. This doesn't happen whether or not my mobile is connected to a VPN (Windscribe in this case). What is surprising is that I can very well log into my account using this app while intercepting traffic with HTTP Toolkit, and I can also see requests made to the app's API on the desktop software. But for sign up, it does not work with HTTP Toolkit enabled.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10 and Zorin OS 16.2

### Details of other apps/devices

Using the Android app "Jeuxvideo.com" modified with apk-mitm.
Using mobile application HTTP Toolkit (latest version downloaded from Google Play) on Android 10.
Using the last version of HTTP Toolkit on Windows and Linux.

**Comment by MrSatisfaction** [comment]
Yes, such errors occur when I hit "Register":
`Certificate rejected for connection to lamssettings-pa.googleapis.com`
`Aborted connection to firebaselogging-pa.googleapis.com`
`Certificate rejected for connection to android.apis.google.com`
`Certificate rejected for connection to play-fe.googleapis.com`
`Certificate rejected for connection to beacons.gvt2.com`
`Certificate rejected for connection to ssl.google-analytics.com`
`Aborted connection to www.google.com`

I tried using Frida with an emulated mobile on my laptop, however trunning the script that bypasses certificate pinning resulted in the following error:

```
Process crashed: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080306

***
FATAL EXCEPTION: main
Process: com.jeuxvideo, PID: 7668
android.view.InflateException: Binary XML file line #27 in com.jeuxvideo:layout/fragment_welcome: Binary XML file line #27 in com.jeuxvideo:layout/fragment_welcome: Error inflating class ImageView
Caused by: android.view.InflateException: Binary XML file line #27 in com.jeuxvideo:layout/fragment_welcome: Error inflating class ImageView
Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f080306
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080306
        at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:273)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:850)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:681)
        at android.content.res.Resources.loadDrawable(Resources.java:1004)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1017)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:991)
        at android.widget.ImageView.<init>(ImageView.java:205)
        at android.widget.ImageView.<init>(ImageView.java:191)
        at androidx.appcompat.widget.AppCompatImageView.<init>(SourceFile:3)
        at androidx.appcompat.widget.AppCompatImageView.<init>(SourceFile:2)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(Unknown Source:2)
        at androidx.appcompat.app.AppCompatViewInflater.createView(SourceFile:251)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(SourceFile:155)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(SourceFile:1)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:244)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.jeuxvideo.ui.fragment.welcome.WelcomeFragment.onCreateView(SourceFile:5)
        at androidx.fragment.app.Fragment.performCreateView(SourceFile:20)
        at androidx.fragment.app.FragmentStateManager.createView(SourceFile:199)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:125)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:231)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:82)
        at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:22)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:39)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(SourceFile:12)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
        at androidx.fragment.app.FragmentActivity.onStart(SourceFile:21)
        at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
        at com.webedia.core.ads.interstitial.activities.EasyBaseInterstitialActivity.onStart(SourceFile:1)
        at v3.d.onStart(SourceFile:1)
        at com.jeuxvideo.ui.activity.WelcomeActivity.onStart(SourceFile:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
        at android.app.Activity.performStart(Activity.java:8628)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
```

And the application suddenly closes after a few seconds everytime I open it.

**Comment by pimterry** [comment]
Hard to say I'm afraid. I don't know any good reason why the app would crash like that - the hooks in the Frida script shouldn't affect anything related to resource loading. No idea, sorry!
