### ISSUE TITLE
[Bug]: Pixel 7 Pro rooted system certificate injection failed

### ISSUE THREAD

**Issue by ABSAhmad** [httptoolkit/httptoolkit#501]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open app on rooted Pixel 7 Pro (tested on latest android 13 and android 14 versions, both with the same issue)
2. Start adb interception in httptoolkit

Error logs:
```
Injecting certificates into APEX cacerts
nsenter: setns: Invalid argument`
Error: System certificate injection failed
    at injectSystemCertificate (/Users/absahmad/Projects/httptoolkit-server/src/interceptors/android/adb-commands.ts:361:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidAdbInterceptor.injectSystemCertIfPossible (/Users/absahmad/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:213:17)
    at AndroidAdbInterceptor.activate (/Users/absahmad/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:69:9)
    at ApiModel.activateInterceptor (/Users/absahmad/Projects/httptoolkit-server/src/api/api-model.ts:177:28)
    at /Users/absahmad/Projects/httptoolkit-server/src/api/rest-api.ts:81:24
    at /Users/absahmad/Projects/httptoolkit-server/src/api/rest-api.ts:173:20
```

When I run `nsenter --help` with root on adb, I get the following output:
```
130|cheetah:/ # nsenter --help
Toybox 0.8.9-android multicall binary (see toybox --help)

usage: nsenter [-t pid] [-F] [-i] [-m] [-n] [-p] [-u] [-U] COMMAND...

Run COMMAND in an existing (set of) namespace(s).

-a	Enter all supported namespaces (--all)
-F	don't fork, even if -p is used (--no-fork)
-t	PID to take namespaces from    (--target)

The namespaces to switch are:

-C	Control groups (--cgroup)
-i	SysV IPC: message queues, semaphores, shared memory (--ipc)
-m	Mount/unmount tree (--mount)
-n	Network address, sockets, routing, iptables (--net)
-p	Process IDs and init, will fork unless -F is used (--pid)
-u	Host and domain names (--uts)
-U	UIDs, GIDs, capabilities (--user)

If -t isn't specified, each namespace argument must provide a path
to a namespace file, ala "-i=/proc/$PID/ns/ipc"
```

From that I can gather that the issue seems to be the `--bind` parameter as that apparently isn't supported but my knowledge regarding this is too limited to work out what the alternative would be.
But I'm happy to test out any changes/suggestions :)

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 13.6

**Comment by ABSAhmad** [comment]
Sure thing, here are the full logs:

```
--- Launching HTTP Toolkit desktop v1.14.5 ---
Config checked in 5 ms
Certificates setup in 8 ms
Standalone server started in 5 ms
Server started in 21 ms
Total startup took 40 ms
INFO: Initialising UI (version 97cfd47587a15a13c3c27c108f20b52e837a85f5)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
(node:32097) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Mock session started, http on port 8000, webrtc enabled
Webextension installed at /var/folders/j7/c7k8l08n767clg_lv1dh6wn80000gq/T/httptoolkit-webextension
Connected to Docker
Updating all Docker network aliases...
INFO: Server started
INFO: API store initialized
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.14.5)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Send store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.5
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.5
Browser cache updated
INFO: Service worker loaded
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
    at /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:19792
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async Promise.all (index 3)
    at async e.getRootCommand (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:21671)
    at async e.AndroidAdbInterceptor.injectSystemCertIfPossible (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:30563)
    at async e.AndroidAdbInterceptor.activate (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:28391)
    at async e.ApiModel.activateInterceptor (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:890:754332)
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:3509
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:2198
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
    at /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:19792
    at async Promise.all (index 4)
    at async e.getRootCommand (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:21671)
    at async e.AndroidAdbInterceptor.injectSystemCertIfPossible (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:30563)
    at async e.AndroidAdbInterceptor.activate (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:28391)
    at async e.ApiModel.activateInterceptor (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:890:754332)
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:3509
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:2198
Adding cert file as /data/local/tmp/4f74014f.0
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-inject-system-cert.sh' ] returned `System cacerts setup completed
Injecting certificates into APEX cacerts
nsenter: setns: Invalid argument`
Error: System certificate injection failed
    at e.injectSystemCertificate (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:26497)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.AndroidAdbInterceptor.injectSystemCertIfPossible (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:31025)
    at async e.AndroidAdbInterceptor.activate (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:28391)
    at async e.ApiModel.activateInterceptor (/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:890:754332)
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:3509
    at async /Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/bundle/index.js:944:2198
INFO: Previous server version was 1.14.5
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed

Android command [ 'su', '-c', 'am force-stop com.android.chrome' ] returned ``
Android Chrome flags set
```

`pidof zygote` returns "1|" weirdly it does that on the second line.
```
cheetah:/ # pidof zygote
1|cheetah:/ #
```

`pidof zygote64` actually seems to return something.
```
cheetah:/ # pidof zygote64
903 1463
```

**Comment by pimterry** [comment]
Woah, that's the problem - `pidof zygote64` is returning two values. That's definitely unexpected! I certainly thought there would only be a single zygote process of each type (one 32 bit, one 64 bit), and breaking that assumption will definitely cause this error. Hmm.

Does this always happen? If you reboot the device, are there still two ids returned there?

I've just pushed a possible fix for this here: https://github.com/httptoolkit/httptoolkit-server/commit/8577f6a683ac8723d3c27eb62d8e83f25d809ff4. Could you test that? You'll need to check the server out and run it manually locally (see the README in that repo) and then open `app.httptoolkit.tech` in Chrome to load the UI and test ADB setup.

You'll need to reboot your device first, since I think otherwise the server will think setup has already been run. You can check what's happening in the logs, it should show "Injecting certificates into APEX cacerts" etc when the full setup is running, or "Cert already installed, nothing to do" if it's skipped.

**Comment by ABSAhmad** [comment]
> Does this always happen? If you reboot the device, are there still two ids returned there?
Just tested it and yes, it seems so:

Executed right after a reboot
```
cheetah:/ # pidof zygote64
1141 1650
```

The applied fix seems to be working:
```
> httptoolkit-server@1.14.5 start
> node-dev ./bin/run start

Config checked in 7 ms
Certificates setup in 3 ms
Standalone server started in 2 ms
Server started in 7 ms
Total startup took 19 ms
Browser cache updated
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT /var/run/docker.sock
Webextension installed at /var/folders/j7/c7k8l08n767clg_lv1dh6wn80000gq/T/httptoolkit-webextension
httptoolkit-server: Updating CLI... !
Failed to check for updates due to 404 response from https://github.com/httptoolkit/httptoolkit-server/releases/download/latest-manifest/darwin-arm64
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/adb-commands.ts:129:37
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at async Promise.all (index 3)
    at getRootCommand (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/adb-commands.ts:190:34)
    at AndroidAdbInterceptor.injectSystemCertIfPossible (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:190:25)
    at AndroidAdbInterceptor.activate (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:69:9)
    at ApiModel.activateInterceptor (/Users/a.el-bardan/Projects/httptoolkit-server/src/api/api-model.ts:177:28)
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/api/rest-api.ts:81:24
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/api/rest-api.ts:173:20
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/adb-commands.ts:129:37
    at async Promise.all (index 4)
    at getRootCommand (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/adb-commands.ts:190:34)
    at AndroidAdbInterceptor.injectSystemCertIfPossible (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:190:25)
    at AndroidAdbInterceptor.activate (/Users/a.el-bardan/Projects/httptoolkit-server/src/interceptors/android/android-adb-interceptor.ts:69:9)
    at ApiModel.activateInterceptor (/Users/a.el-bardan/Projects/httptoolkit-server/src/api/api-model.ts:177:28)
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/api/rest-api.ts:81:24
    at /Users/a.el-bardan/Projects/httptoolkit-server/src/api/rest-api.ts:173:20
Adding cert file as /data/local/tmp/4f74014f.0
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
httptoolkit-server: Updating CLI... !
Failed to check for updates due to 404 response from https://github.com/httptoolkit/httptoolkit-server/releases/download/latest-manifest/darwin-arm64
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-inject-system-cert.sh' ] returned `System cacerts setup completed
Injecting certificates into APEX cacerts
Zygote APEX certificates remounted
APEX certificates remounted for 174 apps
System cert successfully injected`
Cert injected
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed
```

Thanks for the quick reaction and fix :)

**Comment by pimterry** [comment]
Ok, great! That's perfect, glad that's working for you now.

I'd like to wait for a couple of things before the next release here, but I should have this fix in production late this week or early next week. In the meantime you'll need to use the local dev mode as a workaround I'm afraid, but I'll try to get things sorted to get this fixed in the proper release soon! I'll keep this issue open until that's released and resolved.
