### ISSUE TITLE
[Bug]: Http ToolKit doesn't connect to Redroid emulator

### ISSUE THREAD

**Issue by asafe199** [httptoolkit/httptoolkit#532]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Hi! I'm using [redroid](https://github.com/remote-android/redroid-doc), it's an emulator which runs on docker. 
I choosed the image Android 11 latest, everything seems works well, but when I click on `Android Device via ADB` the Http app crash.

I saw two attempts which have failed:
```shell
11-29 13:59:01.271 13327 13742 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.2.2: java.net.SocketTimeoutException: failed to connect to /10.0.2.2 (port 8001) from /192.168.48.2 (port 42200) after 2000ms
11-29 13:59:01.313 13327 13741 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.3.2: java.net.SocketTimeoutException: failed to connect to /10.0.3.2 (port 8001) from /192.168.48.2 (port 59980) after 2000ms
``` 

Below have more logs from ADB and Developer Tools

### How often does this bug happen?

Every time

### The desktop OS you're using

Ubuntu 20.04.6 LTS - x64

### Error screenshot

![Screenshot from 2023-11-29 11-11-48](https://github.com/httptoolkit/httptoolkit/assets/39995089/595c2fa7-c1dc-423d-8e96-b2f6d5872a5d)
![Screenshot from 2023-11-29 11-17-10](https://github.com/httptoolkit/httptoolkit/assets/39995089/dc6291b9-ac2f-4fd2-843e-4a71d3190108)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```shell
1-29 13:58:58.877 13327 13327 I tech.httptoolkit.android.MainActivity: Connecting to VPN from URL: https://android.httptoolkit.tech/connect/?data=eyJhZGRyZXNzZXMiOlsiMTAuMC4yLjIiLCIxMC4wLjMuMiIsIjE5Mi4xNjguMS4xMiJdLCJwb3J0Ijo4MDAxLCJsb2NhbFR1bm5lbFBvcnQiOjgwMDEsImNlcnRGaW5nZXJwcmludCI6InpBTDIvRkt6aUZuM1RhcE8xZE43alZLYXU4dGdHcmlaYXpmN0NVcGphbEE9In0=
11-29 13:58:58.877 13327 13740 D tech.httptoolkit.android.ProxySetup: URL data is {"addresses":["10.0.2.2","10.0.3.2","192.168.1.12"],"port":8001,"localTunnelPort":8001,"certFingerprint":"zAL2/FKziFn3TapO1dN7jVKau8tgGriZazf7CUpjalA="}
11-29 13:58:58.890 13727 13727 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
11-29 13:58:58.891 13727 13727 I AndroidRuntime: Using default boot image
11-29 13:58:58.891 13727 13727 I AndroidRuntime: Leaving lock profiling enabled
11-29 13:58:58.892 13727 13727 I app_process: Core platform API reporting enabled, enforcing=false
11-29 13:58:58.923 13727 13727 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
11-29 13:58:58.923 13727 13727 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
11-29 13:58:58.925 13727 13727 W app_process: Unexpected CPU variant for X86 using defaults: x86_64
11-29 13:58:58.926 13727 13727 I app_process: The ClassLoaderContext is a special shared library.
11-29 13:58:58.931 13727 13727 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-29 13:58:58.934 13727 13727 D AndroidRuntime: Calling main entry com.android.commands.input.Input
11-29 13:58:58.936 13727 13727 D AndroidRuntime: Shutting down VM
11-29 13:58:59.010   225   279 E SchedPolicy: Failed to find cgroup for tid 225
11-29 13:58:59.022   225   279 I chatty  : uid=1000(system) android.bg identical 6 lines
11-29 13:58:59.022   225   279 E SchedPolicy: Failed to find cgroup for tid 225
11-29 13:58:59.208    68    68 D hwcomposer: VSYNC event status:0
11-29 13:58:59.265 13327 13740 V tech.httptoolkit.android (kotlinx.coroutines.SupervisorCoroutine): Validating proxy info ProxyInfo(addresses=[10.0.2.2, 10.0.3.2, 192.168.1.12], port=8001, localTunnelPort=8001, certFingerprint=zAL2/FKziFn3TapO1dN7jVKau8tgGriZazf7CUpjalA=)
11-29 13:58:59.266 13327 13740 V tech.httptoolkit.android (kotlinx.coroutines.SupervisorCoroutine): Proxy tests started
11-29 13:58:59.268 13327 13741 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 10.0.3.2:8001
11-29 13:58:59.268 13327 13765 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 192.168.1.12:8001
11-29 13:58:59.268 13327 13742 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 10.0.2.2:8001
11-29 13:58:59.829   136   165 E Netd    : Failed to dump IPv4 sockets struct tcp_info: No such file or directory
11-29 13:58:59.829   136   165 E TcpSocketMonitor: Failed to poll TCP socket info: No such file or directory
11-29 13:59:00.000   472   472 D KeyguardClockSwitch: Updating clock: 159
11-29 13:59:00.000    68    68 D hwcomposer: VSYNC event status:1
11-29 13:59:00.011   472   472 D KeyguardClockSwitch: Updating clock: 159
11-29 13:59:00.341    68    68 D hwcomposer: VSYNC event status:0
11-29 13:59:01.271 13327 13742 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.2.2: java.net.SocketTimeoutException: failed to connect to /10.0.2.2 (port 8001) from /192.168.48.2 (port 42200) after 2000ms
11-29 13:59:01.313 13327 13741 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.3.2: java.net.SocketTimeoutException: failed to connect to /10.0.3.2 (port 8001) from /192.168.48.2 (port 59980) after 2000ms
11-29 13:59:01.314 13327 13741 I tech.httptoolkit.android.MainActivity: Connect to VPN
11-29 13:59:01.315    68    68 D hwcomposer: VSYNC event status:1
11-29 13:59:01.316 13327 13741 I tech.httptoolkit.android.MainActivity: no intent
11-29 13:59:01.341    68    87 D hwcomposer: hw_composer sent 23 syncs in 61s
11-29 13:59:01.398 13327 13741 I tech.httptoolkit.android.ProxySetup: Proxy cert aliases: [system:4f74014f.0]
11-29 13:59:01.398 13327 13741 I tech.httptoolkit.android.MainActivity: onActivityResult: start-vpn - result: ok
11-29 13:59:01.398 13327 13741 I tech.httptoolkit.android.MainActivity: Installing cert...
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.ProxySetup: Proxy cert aliases: [system:4f74014f.0]
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: Certificate already trusted, continuing
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: onActivityResult: install-cert - result: ok
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: Cert installed, checking notification perms...
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: onActivityResult: enable-notifications - result: ok
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: Notifications OK, starting VPN...
11-29 13:59:01.449 13327 13741 I tech.httptoolkit.android.MainActivity: Starting VPN
11-29 13:59:01.477 13327 13327 I tech.httptoolkit.android.ProxyVpnService: onStartCommand called
11-29 13:59:01.477 13327 13327 I tech.httptoolkit.android.ProxyVpnService: tech.httptoolkit.android.START_VPN_ACTION
11-29 13:59:01.481   225  7667 E VpnJni  : Cannot allocate TUN: Bad file descriptor
11-29 13:59:01.481 13327 13327 D AndroidRuntime: Shutting down VM
11-29 13:59:01.481 13327 13327 E AndroidRuntime: FATAL EXCEPTION: main
11-29 13:59:01.481 13327 13327 E AndroidRuntime: Process: tech.httptoolkit.android.v1, PID: 13327
11-29 13:59:01.481 13327 13327 E AndroidRuntime: java.lang.RuntimeException: Unable to start service tech.httptoolkit.android.ProxyVpnService@207ce16 with Intent { act=tech.httptoolkit.android.START_VPN_ACTION cmp=tech.httptoolkit.android.v1/tech.httptoolkit.android.ProxyVpnService (has extras) }: java.lang.IllegalStateException: Cannot create interface
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Cannot create interface
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:2868)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.net.VpnService$Builder.establish(VpnService.java:897)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at tech.httptoolkit.android.ProxyVpnService.startVpn(ProxyVpnService.kt:226)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at tech.httptoolkit.android.ProxyVpnService.onStartCommand(ProxyVpnService.kt:87)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	... 8 more
11-29 13:59:01.481 13327 13327 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at com.android.server.connectivity.Vpn.jniCreate(Native Method)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at com.android.server.connectivity.Vpn.establish(Vpn.java:1341)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:4571)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1194)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
11-29 13:59:01.481 13327 13327 E AndroidRuntime: 
11-29 13:59:01.482 13327 13327 D io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
11-29 13:59:01.484 13327 13327 I TetheringManager: registerTetheringEventCallback:tech.httptoolkit.android.v1
11-29 13:59:01.680    68    68 D hwcomposer: VSYNC event status:0
11-29 13:59:10.685   725   971 E TcpSocketTracker: Expect to get family 10 SOCK_DIAG_BY_FAMILY message but get 2
11-29 13:59:10.685   725   971 E TcpSocketTracker: Expect to get family 2 SOCK_DIAG_BY_FAMILY message but get 2
11-29 13:59:21.473   225   280 W ActivityManager: Timeout executing service: ServiceRecord{cb59146 u0 tech.httptoolkit.android.v1/tech.httptoolkit.android.ProxyVpnService}
11-29 13:59:21.478   225 13878 I ActivityManager: dumpStackTraces pids={449=true, 491=true, 567=true, 855=true, 1035=true, 1128=true, 1152=true, 1246=true, 1277=true, 1396=true, 1416=true, 1641=true, 1748=true, 1777=true, 2116=true, 2535=true, 2562=true, 9345=true, 11337=true, 12330=true, 12432=true} nativepids=[27, 74, 79, 114, 115, 132, 134, 135, 136, 140, 142, 143, 449]
11-29 13:59:21.697   225 13878 I ActivityManager: Skipping next CPU consuming process, not a java proc: 225
11-29 13:59:21.698   225 13878 I ActivityManager: Dumping to /data/anr/anr_2023-11-29-13-59-21-697
11-29 13:59:21.698   225 13878 I ActivityManager: Collecting stacks for pid 13327
11-29 13:59:21.699   225 13878 I system_server: libdebuggerd_client: started dumping process 13327
11-29 13:59:21.699    49    49 I tombstoned: registered intercept for pid 13327 and type kDebuggerdJavaBacktrace
11-29 13:59:21.700 13327 13337 I lkit.android.v: Thread[6,tid=13337,WaitingInMainSignalCatcherLoop,Thread*=0x7f9d6a7922c0,peer=0x12c401b0,"Signal Catcher"]: reacting to signal 3
11-29 13:59:21.700 13327 13337 I lkit.android.v: 

```

**Comment by pimterry** [comment]
> I saw two attempts which have failed

Those connection errors aren't a problem - that's the app testing different possible IPs. You can see that 3 are provided in the logs, those two fail but `192.168.1.12` works correctly.

The problem is this:

```
VpnJni  : Cannot allocate TUN: Bad file descriptor
AndroidRuntime: java.lang.RuntimeException: Unable to start service tech.httptoolkit.android.ProxyVpnService@207ce16 with Intent { act=tech.httptoolkit.android.START_VPN_ACTION cmp=tech.httptoolkit.android.v1/tech.httptoolkit.android.ProxyVpnService (has extras) }: java.lang.IllegalStateException: Cannot create interface
```

I've never used Redroid, but based on that it looks like it doesn't support Android's VPN APIs by default.

https://github.com/remote-android/redroid-doc/issues/495 suggests that you may be able to configure your Redroid setup to work around this. I've never tested that, you'll need to investigate it yourself I'm afraid, and debug any issues with that with the Redroid team.

If you can't get that working, in this configuration you may have more success using the new Frida scripts: https://github.com/httptoolkit/frida-interception-and-unpinning/. You'd need to first install Frida inside the emulator, but those can then provide interception functionality without using any VPN setup, and without needing the HTTP Toolkit Android app at all. This isn't fully automated yet but it's planned to be properly integrated into HTTP Toolkit in future. I've written a general guide to getting started with Frida here: https://httptoolkit.com/blog/frida-certificate-pinning/.
