### ISSUE TITLE
Support for rootless docker/podman containers

### ISSUE THREAD

**Issue by dominiwe** [httptoolkit/httptoolkit#656]
For a while now, it has been possible to use docker in [rootless mode](https://docs.docker.com/engine/security/rootless/). The [same is true for Podman](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md). I think it would be nice to be able to intercept rootless containers.

From just a quick google search, it seems these projects use [pasta](https://passt.top/passt/about/#pasta-pack-a-subtle-tap-abstraction) ([quote from here](https://docs.podman.io/en/stable/markdown/podman-run.1.html)):

> pasta[:OPTIONS,…]: use pasta(1) to create a user-mode networking stack.
This is the default for rootless containers and only supported in rootless mode. 

Using podman, I was able to pass arguments to pasta to generate a pcap capture just like so when running a container:

```sh
podman run --rm -it --network=pasta:--pcap,capture.pcap alpine sh
```

So there seems to be some support to capture traffic already. But I am unsure of how hard this is for an already running container.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
A PCAP isn't enough unfortunately - that's fine for inspecting raw traffic, but if you want to inspect TLS you'll need the keys somehow (which means hooking the container internals) and then if you want to modify the traffic then you have to be on the request path directly instead of just reading a recording.

That said, it should be possible to intercept rootless containers (docker or podman) just like the existing docker support in theory, there's no particular reason it's much more difficult, it's just an issue of configuration on the details.

The details are a tricky though. HTTP Toolkit mainly works by intercepting the calls to the Docker API using DOCKER_HOST env var, and assumes the real API is exposed either on the root docker socket e.g. at `/var/run/docker.sock` or an existing DOCKER_HOST variable. For basics of interception there's not much network reconfiguration required (only to route traffic into/between containers, not intercept traffic on the way out).

I don't have a test env set up for this right now. Do you? What's the current behaviour using HTTP Toolkit?

**Comment by dominiwe** [comment]
Thanks for the information! Interesting.

I do have multiple setups with podman and docker, both rootless and normal that I could test with. The current behaviour for me is that the _Attach to Docker Container_ option is greyed out. I tried the following:

```bash
# with rootless podman
DOCKER_HOST=/var/run/user/1000/podman/podman.sock httptoolkit

# with rootless docker
DOCKER_HOST=/var/run/user/1000/docker.sock httptoolkit
```

To be able to do this with podman, I tried out the [socket activation](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md).

**Comment by pimterry** [comment]
Looks like the DOCKER_HOST format actually needs to be a proper URL (examples [here](https://stackoverflow.com/a/62757128/68051)). In this case, I think they need a `unix://` prefix (plus the leading path slash too, e.g. `unix:///var/run/user/1000/podman/podman.sock`).

Does that work?

If not, if you look at the logs after launching HTTP Toolkit like this, is there anything interesting there? Those are available under Help -> View HTTP Toolkit Logs. Every startup, it should log one of:

* `Connected to Docker at <address>`
* `Docker not available: <error message>`

The actual detection is [here](https://github.com/httptoolkit/httptoolkit-server/blob/211f45a09538dfb3336f82c5f3a38da4e334133a/src/interceptors/docker/docker-interception-services.ts#L27-L52) - it's just a call to [Dockerode](https://github.com/apocas/dockerode)'s `new Docker().info()`. Doing it a little digging, it definitely looks Dockerode should support Podman, since it's actually the same Docker client that's used in podman-desktop ([here](https://github.com/podman-desktop/podman-desktop/blob/b90a42db04c19b7fc5e8aa88f2eef6450497330f/package.json#L188)). HTTP Toolkit uses that same client, so API compatibility at least should work OK. It's hard to know if there's features or nuances we depend on that aren't fully available in this case, but I'm not aware of anything specifically that'd cause issues so maybe it'll just work if we can get the initial connection running.

If you find that the above does work, and assuming those are standard paths, the best next step would be a PR to [docker-modem](https://github.com/apocas/docker-modem/) to automatically detect & use those paths if present. Docker-modem is used as the base for all connections in Dockerode, which is used by HTTP Toolkit and many _many_ other tools, so a PR there would probably make sockets at those paths work out of the box for a big chunk of the whole ecosystem.

**Comment by dominiwe** [comment]
Using `DOCKER_HOST=unix:///var/run/user/1000/podman/podman.sock httptoolkit` made the option show up! I could then choose a container but got an error like so:

```
Starting Docker tunnel...
Querying Docker tunnel port...
Error handling request to /interceptors/docker-attach/activate/8000: (HTTP code 500) server error - "" is not supported: invalid network mode
Error: (HTTP code 500) server error - "" is not supported: invalid network mode
    at /home/myuser/.local/share/httptoolkit-server/client/1.19.1/bundle/index.js:2:1385288
    at /home/myuser/.local/share/httptoolkit-server/client/1.19.1/bundle/index.js:2:1385228
    at Q.buildPayload (/home/myuser/.local/share/httptoolkit-server/client/1.19.1/bundle/index.js:2:1385238)
    at IncomingMessage.<anonymous> (/home/myuser/.local/share/httptoolkit-server/client/1.19.1/bundle/index.js:2:1384552)
    at IncomingMessage.emit (node:events:530:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'server error',
  statusCode: 500,
  json: {
    cause: 'invalid network mode',
    message: '"" is not supported: invalid network mode',
    response: 500
  }
}
Error reporting timed out
```

In a intercepted terminal it also doesn't work, as there appears to just be no internet in a rootless container launched from there.

I will test with rootless docker on my other laptop when I get home.
